langurage: python
python:
 - "2.7"
 - "2.6"
 - "3.3"
install:
 - pip install . --use-mirrors
branches:
 only:
  - master
script: python manage.py test account socialaccount dropbox facebook google github linkedin openid persona soundcloud stackexchange twitch twitter weibo 