langurage: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
env:
 - DJANGO_VERSION=1.4.3
 - DJANGO_VERSION=1.5
install:
 - pip install -q Django==$DJANGO_VERSION
 - pip install . --use-mirrors
branches:
 only:
  - master
script: python manage.py test account socialaccount dropbox facebook google github linkedin openid persona soundcloud stackexchange twitch twitter weibo 