sudo: false
language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
env:
  matrix:
   - DJANGO="Django<1.7"
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
install:
 - pip install $DJANGO --use-mirrors
 - pip install . --use-mirrors
 - pip install https://bitbucket.org/yrikk/coveragepy/get/yrikk/remove-unnecessary-u-prefixes-for-better-1442777261357.zip?
branches:
 only:
  - master
script: coverage run manage.py test allauth
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
