sudo: false
language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
env:
  matrix:
   - DJANGO="Django<1.7"
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
   - DJANGO="Django==1.9b1"
install:
 - pip install $DJANGO
 - pip install .
 - pip install coverage==3.7.1
matrix:
  allow_failures:
   - env: DJANGO="Django==1.9b1"
  # TODO: Remove when https://github.com/necaris/python3-openid/issues/16 is resolved.
   - python: "3.5"
  exclude:
    - python: "3.5"
      env: DJANGO="Django<1.8"
branches:
 only:
  - master
script: coverage run manage.py test allauth
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
